name: 'Get & Cache Dependencies'
description: 'Get dependencies (via npm) and cache them.'
inputs:
  caching:
    description: 'Whether to cache or not'
    required: false
    default: 'true'
outputs:
  used-cache:
    description: 'Did we use the cache?'
    value: ${{ steps.install.outputs.cache }}
runs:
  using: 'composite'
  steps:
    - name: Cache dependencies
      if: inputs.caching == 'true'
      id: cache
      uses: actions/cache@v3
      with:
        path: node_modules
        key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
    - name: Install dependencies
      if: steps.cache.outputs.cache-hit != 'true' || inputs.caching != 'true'
      id: install
      run: |
        npm ci
        echo "cache='${{inputs.caching}}'" >> $GITHUB_OUTPUT
      shell: bash